spring:
  application:
    name: pop
  datasource:
    url: jdbc:mysql://localhost:3306/pop?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.pop.vo
  configuration:
    map-underscore-to-camel-case: true
